### ISSUE TITLE
Add a text version of the "Supported Glyphs" image

### ISSUE THREAD

**Issue by Damnjelly** [molarmanful/kirsch#2]
I would like to use some of the special characters in my configuration but I find it difficult to figure out which gylphs are supported, i think a text version of the "Supported Glyphs" image, [like the one included in Cozette](https://github.com/slavfox/Cozette/blob/main/img/charmap.txt) would help a lot with that.

Loving the font btw, its super pretty!

**Comment by molarmanful** [comment]
Great idea, I'll see what I can put together!

**Comment by molarmanful** [comment]
I've just pushed glyphmaps to `txt/` and `img/`. Please let me know if there's anything you need tweaked.

**Comment by Damnjelly** [comment]
This is exactly what i was looking for! Thanks a lot!
