### ISSUE TITLE
Whitespace after all characters in kirsch2x and kirsch 3x obt's

### ISSUE THREAD

**Issue by Damnjelly** [molarmanful/kirsch#3]
The 2x and 3x variants of kirsch have an extra white space added after every character. The 1x variant of kirsch does not seem to have this issue. From my investigation this occured sometime between release 0.0.2 and 0.0.5. Below an image showing the difference between kirsch2x on 0.0.2 (left), and kirsch2x on 0.0.5 (right):

![image](https://github.com/molarmanful/kirsch/assets/13944407/a2a5fbfa-488c-4c4f-987f-1d06eb3f2184)

**Comment by molarmanful** [comment]
Hi, thanks for raising this issue. I have a hunch as to where the issue is (probably somewhere around the FontForge part of the build process), but I'll do some more digging.

**Comment by molarmanful** [comment]
Alright figured it out, seems like either FontForge or bdfresize does something wrong with scalable width calculations. Either way, [this release should hopefully solve it](https://github.com/molarmanful/kirsch/releases/tag/v0.0.6) 🙏

**Comment by Damnjelly** [comment]
Updated Kirsch and it seems good now, thanks!
